<div class="row">
	<div class="col-lg-12">
		<div class="small float-left col-md-3 m-l-lg m-t-md">
			<strong>Sales char</strong> have evolved over the years sometimes.
		</div>
		<div class="small float-right col-md-3 m-t-md text-right">
			<strong>There are many</strong> variations of passages of Lorem Ipsum available, but the majority have suffered.
		</div>
		<div class="flot-chart m-b-xl">
			<div class="flot-chart-content" id="flot-dashboard5-chart" style="padding: 0px; position: relative;"><canvas class="flot-base" width="1263" height="200" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 1263px; height: 200px;"></canvas><div class="flot-text" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; font-size: smaller; color: rgb(84, 84, 84);"><div class="flot-x-axis flot-x1-axis xAxis x1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px;"><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 17px; text-align: center;">0</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 171px; text-align: center;">2</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 326px; text-align: center;">4</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 480px; text-align: center;">6</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 635px; text-align: center;">8</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 786px; text-align: center;">10</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 941px; text-align: center;">12</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 1095px; text-align: center;">14</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 140px; top: 182px; left: 1250px; text-align: center;">16</div></div><div class="flot-y-axis flot-y1-axis yAxis y1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px;"><div class="flot-tick-label tickLabel" style="position: absolute; top: 169px; left: 8px; text-align: right;">0</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 135px; left: 8px; text-align: right;">5</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 101px; left: 2px; text-align: right;">10</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 68px; left: 2px; text-align: right;">15</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 34px; left: 2px; text-align: right;">20</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 0px; left: 2px; text-align: right;">25</div></div></div><canvas class="flot-overlay" width="1263" height="200" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 1263px; height: 200px;"></canvas></div>
		</div>
	</div>
</div>